# -*- coding: utf-8 -*-
"""Basis, Orthogonal, and Orthonormal Vectors Dino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1me5Fop0MKJh9vCVVUb_vW2K1lcHbTkcJ

### Orthogonal Vectors
"""

import numpy as np

i = np.array([1, 0])
i

j = np.array([0, 1])
j

np.dot(i, j)

v = np.array([1, 2])
v

w = np.array([2, -1])
w

np.dot(v, w)