# -*- coding: utf-8 -*-
"""Exercises On Algebra Data Structures Dino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3dEZJrLcVtuPSMUs0n1mwvKa4Y9P9yw
"""

import numpy as np

x = np.array([[25],
               [2],
              [-3],
              [-23]])
x

x_t = x.T
x_t