# -*- coding: utf-8 -*-
"""Generic Tensor Notation Dino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhqTe6L0GJcFmsCYjZB8wQ8BuK_uYW0F
"""

import torch
import tensorflow as tf

images_pt = torch.zeros([32, 28, 28, 3])

images_pt

images_tf = tf.zeros([32, 28, 28, 3])

images_tf