# -*- coding: utf-8 -*-
"""Matrix Tensors Dino.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nw22IUraZSFGRaJGBvNN-4zairJ0gf8
"""

import numpy as np

X = np.array([[15, 2], [5, 13], [3, 9]])
X

X.shape

X.size

X[:,0]

X[1,:]

X[0:2, 0:2]

import torch

X_pt = torch.tensor([[15, 2], [5, 13], [3, 9]])
X_pt

X_pt.shape

X_pt[1,:]

import tensorflow as tf

X_tf = tf.Variable([[15, 2], [5, 13], [3, 9]])
X_tf

tf.rank(X_tf)

tf.shape(X_tf)

X_tf[1,:]