# -*- coding: utf-8 -*-
"""Norms and Unit Vector Dino1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBDJ9OOSJEHR7tlcPZNMisFmQgZoM5rP
"""

import numpy as np

x = np.array([15, 5, 10])

x

(15**2 + 5**2 + 10**2)**(1/2)

np.linalg.norm(x)

x

np.abs(15) + np.abs(5) + np.abs(10)

x

(15**2 + 5**2 + 10**2)

np.dot(x, x)

x

np.max([np.abs(15), np.abs(5), np.abs(10)])

v = np.array([3, 4])

norm = np.linalg.norm(v)

unit_v = v / norm

print("Vektor asli:", v)
print("Panjang vektor:", norm)
print("Unit vector:", unit_v)
print("Panjang unit vector:", np.linalg.norm(unit_v))

import numpy as np
import matplotlib.pyplot as plt

v = np.array([3, 4])

norm = np.linalg.norm(v)

unit_v = v / norm

plt.figure()

plt.quiver(0, 0, v[0], v[1],
           angles='xy',
           scale_units='xy',
           scale=1,
           color='blue',
           label='Vektor Asli')

plt.quiver(0, 0, unit_v[0], unit_v[1],
           angles='xy',
           scale_units='xy',
           scale=1,
           color='red',
           label='Unit Vector')

plt.xlim(-1, 5)
plt.ylim(-1, 5)
plt.axhline(0)
plt.axvline(0)
plt.gca().set_aspect('equal', adjustable='box')
plt.plot([v[0], v[0]], [0, v[1]], linestyle='--')
plt.plot([0, v[0]], [v[1], v[1]], linestyle='--')


plt.plot([unit_v[0], unit_v[0]], [0, unit_v[1]], linestyle='--')
plt.plot([0, unit_v[0]], [unit_v[1], unit_v[1]], linestyle='--')

plt.scatter(v[0], v[1])
plt.scatter(unit_v[0], unit_v[1])

plt.xlim(-1, 5)
plt.ylim(-1, 5)
plt.axhline(0)
plt.axvline(0)
plt.gca().set_aspect('equal', adjustable='box')

plt.legend()
plt.title("Visualisasi Vektor vs Unit Vector")
plt.show()

