# -*- coding: utf-8 -*-
"""SCALARS_DINO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/dinooRv/Tugas-Koding-Muhammad-Aprila-Dino_2515061090/blob/main/SCALARS_DINO.ipynb
"""

x = 5
x

type(x)

y = 10

type(y)

py_sum = x + y
py_sum

type(py_sum)

x_float = 5.5

float_sum = x_float + y
float_sum

type(float_sum)

import tensorflow as tf

x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

import torch

x_pt = torch.tensor(25)
x_pt

x_pt.shape