# -*- coding: utf-8 -*-
"""Vector & Vector Transposition Dino .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MmKE4D_DTbbW3D2SnmCIit6T6QuY6u5
"""

import numpy as np

x = np.array([15, 5, 10])
x

len(x)

x.shape

type(x)

x[0]

type(x[0])

x_t = x.T
x_t

x_t.shape

y = np.array([[25, 2, 5]])
y

y.shape

y_t = y.T
y_t

y_t.shape

y_t.T

y_t.T.shape

z = np.zeros(3)
z

import torch
import tensorflow as tf

x_pt = torch.tensor([25, 2, 5])
x_pt

x_tf = tf.Variable([25, 2, 5])
x_tf