# -*- coding: utf-8 -*-
"""Tensor Reduction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHc-aYti_d4ddFJCZwmreUzhsvGRyQ_c

Tensor Reduction Soal 1
"""

import numpy as np
import torch
import tensorflow as tf

""" Membuat matrix X (2x3) dengan Numpy"""

X = np.array([[1, 2, 3], [4, 5, 6]])

"""Membuat matrix X_pt (2x3) dengan PyTorch"""

X_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])

"""Membuat matrix X_tf (2x3) denganTensorFlow"""

X_tf = tf.constant([[1, 2, 3], [4, 5, 6]])

print("Matrix X (NumPy):\n", X)

"""Tensor Reduction Soal 2

Penjualan seluruh elemen X (NumPy)
"""

sum_X = np.sum(X)

"""Penjumlahan seluruh elemen X_pt (PyTorch)"""

sum_pt = torch.sum(X_pt)

"""Penjumlahan seluruh elemen X_tf (TensorFlow)"""

sum_tf = tf.reduce_sum(X_tf)

print(f"Total Sum -> NumPy: {sum_X}, PyTorch: {sum_pt.item()}, TF: {sum_tf.numpy()}")

"""Tensor Reduction Soal 3

NumPy Berdasarkan row (axis=1)
"""

row_sum_X = np.sum(X, axis=1)

"""PyTorch Berdasarakan row (din=1)"""

row_sum_pt = torch.sum(X_pt, dim=1)

"""TensorFlow berdasarkan row (axis=1)"""

row_sum_tf = tf.reduce_sum(X_tf, axis=1)

row_sum_pt = torch.sum(X_pt, dim=1)
row_sum_tf = tf.reduce_sum(X_tf, axis=1)
print(f"Row Sum -> NumPy: {row_sum_X}, PyTorch: {row_sum_pt}, TF: {row_sum_tf}")

"""Tensor Reduction soal 4

Numpy berdasarkan kolom (axis=0)
"""

col_sum_X = np.sum(X, axis=0)

"""PyTorch berdasarkan kolom (dim=0)"""

col_sum_pt = torch.sum(X_pt, dim=0)

"""TensorFlow berdasarkan kolom (axis=0)"""

col_sum_tf = tf.reduce_sum(X_tf, axis=0)

print(f"Col Sum -> NumPy: {col_sum_X}, PyTorch: {col_sum_pt}, TF: {col_sum_tf.numpy()}")

"""Tensor Reduction Soal 5

Penentuan nilai minimum pada setiap matrix
"""

min_X = np.min(X)
min_pt = torch.min(X_pt)
min_tf = tf.reduce_min(X_tf)

"""Penentuan nilai maksimum pada setiap matrix"""

max_X = np.max(X)
max_pt = torch.max(X_pt)
max_tf = tf.reduce_max(X_tf)

"""Nilai rata rata matrix"""

mean_X = np.mean(X)
mean_pt = torch.mean(X_pt.float())
mean_tf = tf.reduce_mean(tf.cast(X_tf, tf.float32))

print(f"Min: {min_X}, Max: {max_X}, Mean: {mean_X}")

"""Tensor Reduction soal 6

Perkalian Seluruh elemen X (Numpy)
"""

prod_X = np.prod(X)

"""Perkalian seluruh elemen X_pt (Pytorch)"""

prod_pt = torch.prod(X_pt)

"""Perkalian seluruh elemen X_tf (TensorFlow)"""

prod_tf = tf.reduce_prod(X_tf)

print(f"Product -> NumPy: {prod_X}, PyTorch: {prod_pt.item()}, TF: {prod_tf.numpy()}")